// ==UserScript==
// @name        Blogger Userscript
// @version     0.0.1
// @date        2022-01-25
// @author      Zen
// @description Tools yang akan memudahkan nulis di Blogger
// @homepage    https://www.cuapcuap.my.id
// @updateURL   https://download.sf-helper.com/chrome/helper.meta.js
// @downloadURL https://download.sf-helper.com/chrome/helper.user.js
// @include     http://*
// @include     https://*
// @run-at      document-end
// @grant       GM_listValues
// @grant       GM_setValue
// @grant       GM_getValue
// @grant       GM_deleteValue
// @grant       GM_xmlhttpRequest
// @grant       GM_info
// @grant       GM_openInTab
// @grant       GM_setClipboard
// @grant       GM_registerMenuCommand
// @grant       GM_unregisterMenuCommand
// @grant       GM_notification
// @grant       GM_download
// @grant       GM.info
// @grant       GM.listValues
// @grant       GM.setValue
// @grant       GM.getValue
// @grant       GM.deleteValue
// @grant       GM.openInTab
// @grant       GM.setClipboard
// @grant       GM.xmlHttpRequest
// @connect     vk.com
// @connect     vk.me
// @connect     userapi.com
// @connect     vkuseraudio.net
// @connect     vkuservideo.net
// @connect     vk-cdn.net
// @connect     youtube.com
// @connect     youtube-nocookie.com
// @connect     ytimg.com
// @connect     googlevideo.com
// @connect     video.google.com
// @connect     google-analytics.com
// @connect     api.amplitude.com
// @connect     dailymotion.com
// @connect     vimeo.com
// @connect     vimeocdn.com
// @connect     akamaized.net
// @connect     odnoklassniki.ru
// @connect     ok.ru
// @connect     cdn-ok.com
// @connect     mycdn.me
// @connect     storage.mds.yandex.net
// @connect     twitch.tv
// @connect     sf-helper.net
// @connect     televzr.com
// @connect     127.0.0.1
// @connect     pladform.ru
// @connect     clipyou.ru
// @connect     soundcloud.com
// @connect     sndcdn.com
// @connect     mail.ru
// @connect     176.9.38.116
// @connect     cdninstagram.com
// @connect     fbcdn.net
// @connect     facebook.com
// @connect     sf-helper.com
// @connect     savefr.com
// @connect     travelbar.tools
// @connect     promobar.tools
// @connect     savefrom.net
// @connect     self
// @connect     *
// ==/UserScript==